/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "../Inc/MCAL/RCC/Inc/RCC_private.h"
#include "../Inc/MCAL/RCC/Inc/RCC_interface.h"
#include "../Inc/MCAL/GPIO/GPIO_private.h"
#include "../Inc/MCAL/GPIO/GPIO_interface.h"


int main(void)
{
	/*Enable clock on GPIOA*/
	RCC_Enable_Peripheral(0u);

	/*Configure pinA5 as: output, Pushpull, Nopull, LowSpeed*/
	GPIO_PinConfig_t LedPin =
	{
			.Port = PORTA,
			.PinNum =PIN5,
			.Mode = OUTPUT,
			.OutputType = PUSH_PULL,
			.Speed = LOW,
			.PullType = NOPULL
	};

	GPIO_u8PinInit(&LedPin);

	/*high on the pin to turn on the user led*/
	while(1)
	{
		GPIO_u8SetPinValue(PORTA, PIN5, PIN_HIGH);
		STK_Delay_ms(1000);
		GPIO_u8SetPinValue(PORTA, PIN5, PIN_LOW);
		STK_Delay_ms(1000);
	}

	/* Loop forever */
 	for(;;);
}
